
-- Q1. How many customers are registered on the platform?
select count(*) as totalCustomers from customers_dataset;
-- Q2. How many orders have been placed?
select count(*) as total_Orders from order_products;
-- Q3. How many sellers are active on the platform?
select count(DISTINCT seller_id) as active_salers from order_items_dataset
-- Q4. How many unique products are sold?
select count(DISTINCT product_id) as unique_products from order_products;
-- Q5. What are the different order statuses?
select count(*),order_status from orders_dataset
Group by order_status;
-- Q6. Which product categories are available?
select count(*), product_category_name from order_products
Group by product_category_name;

-- Q7. What is the total revenue generated by Olist?
select sum(payment_value) as total_revenue from order_payments;
-- Q8. What is the average order value?
select avg(payment_value) as avg_order_value from order_payments;
-- Q9. Which months generated the highest revenue?
select count(order_id), sum(payment_value) as total_revenue,month(order_purchase_timestamp) as month from orders_dataset
join order_payments using (order_id)
Group by month
Order by total_revenue desc
Limit 1

-- Q10. Is the marketplace growing over time?

-- Q11. Which year had the highest sales?
select count(DISTINCT order_id), sum(payment_value) as total_revenue,year(order_purchase_timestamp) as year from orders_dataset
join order_payments using (order_id)
Group by year
Order by total_revenue desc
Limit 1

-- Q12. What percentage growth did revenue experience year-over-year?
SELECT YEAR(order_purchase_timestamp) AS year, SUM(payment_value) AS revenue,
((SUM(payment_value) - LAG(SUM(payment_value)) OVER (ORDER BY YEAR(order_purchase_timestamp))) /
LAG(SUM(payment_value)) OVER (ORDER BY YEAR(order_purchase_timestamp))) * 100 AS yoy_growth_pct
FROM orders_dataset
JOIN order_payments USING (order_id)
GROUP BY year
ORDER BY year; 

-- Q13. Which states have the highest number of customers?
select customer_state, count(customer_id) as total_cst_state from customers_dataset 
Group by customer_state
order by total_cst_state desc limit 1
-- Q14. Which cities contribute the most customers?
select customer_city, count(*) as total from customers_dataset 
Group by customer_city
order by total desc limit 1
-- Q15. What is the average spending per customer?
select avg(total) from 
(select sum(payment_value) as total from customers_dataset
join orders_dataset using (customer_id)
join order_payments using(order_id)
Group by customer_id) t
Limit 20
-- Q16. Who are the top 20 customers by total spending?
select customer_id, sum(payment_value) as total, RANK() over (Order by sum(payment_value) desc) from customers_dataset
join orders_dataset using (customer_id)
join order_payments using(order_id)
Group by customer_id
Limit 20
-- Q17. What percentage of customers made repeat purchases?
select ROUND (count(CASE when orders > 1 then 1 end) * 100.0 /  COUNT(*), 2 ) as repeat_purchase_percentage
from ( 
select customer_unique_id, COUNT(order_id) as orders from customers_dataset
join orders_dataset using(customer_id)
Group by customer_unique_id  ) t;

-- Q18. Which customers can be classified as VIP customers?
select customer_id, sum(payment_value) as total, RANK() over (Order by sum(payment_value) desc) from customers_dataset
join orders_dataset using (customer_id)
join order_payments using(order_id)
Group by customer_id
Limit 5

-- Q19. Which product categories generate the highest revenue?
select product_category_name, sum(price) as totalprice from order_items_dataset
join order_products using (product_id)
Group by product_category_name
Order by totalprice desc

-- Q20. Which categories sell the highest number of units?
select product_category_name,count(order_item_id) as unitsold from order_items_dataset
join order_products using (product_id)
Group by product_category_name 
order by unitsold desc
LIMIT 1;

-- Q21. Which product categories are the least popular?
select product_category_name,count(order_item_id) as unitsold from order_items_dataset
join order_products using (product_id)
Group by product_category_name 
order by unitsold asc
LIMIT 1;
-- Q22. Which products contribute the most revenue?
select product_category_name,sum(price) as revenue from order_products
join order_items_dataset using (product_id)
Group by product_category_name

-- Q23. Which categories have high sales but low customer ratings?
select product_category_name,count(order_item_id) as unitsold, avg(review_score) from order_items_dataset
join order_products using (product_id)
join order_reviews using (order_id)
Group by product_category_name 
order by unitsold desc, avg(review_score) asc

-- Q24. Which categories should receive additional marketing investment?
select product_category_name,count(order_item_id) as unitsold from order_items_dataset
join order_products using (product_id)
Group by product_category_name 
order by unitsold asc
Limit 5

-- Q25. Which sellers generate the highest revenue?
select seller_id, sum(price) from order_items_dataset
join sellers_products using (seller_id )
Group by seller_id
Order by sum(price)
Limit 1;

-- Q26. Which sellers process the highest number of orders?
select seller_id, count(order_id) from orders_dataset
join order_items_dataset using (order_id)
join sellers_products using (seller_id)
Group by seller_id
Order by count(order_id) desc

-- Q27. Which sellers have the best customer ratings?
select seller_id, avg(review_score) from order_reviews
join order_items_dataset using (order_id)
join sellers_products using (seller_id)
Group by seller_id
Order by avg(review_score) desc

-- Q28. Which sellers experience consistently poor ratings?
select seller_id, avg(review_score) from order_reviews
join order_items_dataset using (order_id)
join sellers_products using (seller_id)
Group by seller_id
Order by avg(review_score) asc

-- Q29. Which sellers should be recognized as top performers?
select seller_id, avg(review_score) from order_reviews
join order_items_dataset using (order_id)
join sellers_products using (seller_id)
Group by seller_id
Order by avg(review_score) desc
Limit 5;

-- Q30. Which sellers require operational improvements?
select seller_id, avg(review_score) from order_reviews
join order_items_dataset using (order_id)
join sellers_products using (seller_id)
Group by seller_id
Order by avg(review_score) asc
Limit 5;

-- Q31. What is the average delivery time?
select avg(datediff(order_delivered_customer_date,order_purchase_timestamp)) as average_delivery_time from orders_dataset;

-- Q32. Which states experience the longest delivery times?
select customer_state, avg(datediff(order_delivered_customer_date,order_purchase_timestamp)) as average_delivery_time from orders_dataset
join customers_dataset using(customer_id)
Group by customer_state
Order by average_delivery_time desc

-- Q33. Which sellers have the fastest delivery performance?
select seller_id, avg(datediff(order_delivered_customer_date,order_purchase_timestamp)) as average_delivery_time from orders_dataset
join order_items_dataset using (order_id)
join sellers_products using (seller_id)
Group by seller_id
Order by average_delivery_time asc;

-- Q34. Does longer delivery time negatively impact customer reviews?
select review_score, avg(datediff(order_delivered_customer_date,order_purchase_timestamp)) as average_delivery_time from orders_dataset
join order_reviews using (order_id)
Group by review_score
Order by average_delivery_time desc

-- Q35. Which regions face the greatest delivery challenges?
select CASE
when customer_state IN ('SP', 'RJ', 'MG', 'ES') then 'Southeast'
when customer_state IN ('PR', 'RS', 'SC') then 'South'
when customer_state IN ('GO', 'MT', 'MS', 'DF') then 'Central-West'
when customer_state IN ('BA', 'CE', 'RN', 'PE', 'PB', 'PI', 'AL', 'SE', 'MA') then 'Northeast'
when customer_state IN ('PA', 'AM', 'AP', 'RO', 'TO', 'AC', 'RR') then 'North' 
END as Regions,
avg(datediff(order_delivered_customer_date,order_purchase_timestamp)) as average_delivery_time from orders_dataset
join customers_dataset using(customer_id)
GROUP BY Regions
Order by average_delivery_time desc

-- Q36. Are delayed orders associated with lower customer satisfaction?
select review_score, avg(datediff(order_delivered_customer_date,order_purchase_timestamp)) as average_delivery_time from orders_dataset
join order_reviews using (order_id)
Group by review_score
Order by average_delivery_time desc

-- states = SP, SC, MG, PR, RJ, RS, PA, GO,ES,BA,MA,MS,CE,DF,RN,PE,MT,AM,AP,AL,RO,PB,TO,PI,AC,SE,RR
-- Q37. Which payment methods are most frequently used?
select payment_type, count(payment_type) from order_payments
Group by payment_type
-- Q38. Which payment methods contribute the highest revenue?
select payment_type, sum(payment_value) from order_payments
Group by payment_type
order by sum(payment_value) desc
-- Q39. What is the average installment count for each payment type?
select payment_type, avg(payment_installments) as avg_installment_count from order_payments
Group by payment_type

-- Q40. Do customers using installments spend more?                         ????????????????
select count(payment_installments) as avg_installment_count from order_payments
Group by order_id
Order by avg_installment_count desc
-- Q41. Which payment methods should Olist continue promoting?
select payment_type, sum(payment_value) from order_payments
Group by payment_type
order by sum(payment_value) desc

Q42. What is the distribution of review scores?

-- Q43. Which product categories receive the highest ratings?
select product_category_name, avg(review_score) from order_products
join order_items_dataset using (product_id)
join order_reviews using(order_id)
Group by product_category_name
Order by avg(review_score) desc

-- Q44. Which categories receive the lowest ratings?
select product_category_name, avg(review_score) from order_products
join order_items_dataset using (product_id)
join order_reviews using(order_id)
Group by product_category_name
Order by avg(review_score) acs

-- Q45. How do review scores vary by seller?
select seller_id, avg(review_score) from sellers_products
join order_items_dataset using (seller_id)
join order_reviews using(order_id) 
Group by seller_id
Order by avg(review_score) desc

-- Q46. Which factors contribute most to poor customer reviews?
select review_score, avg(datediff(order_delivered_customer_date,order_estimated_delivery_date)) as average_delivery_time from orders_dataset
join order_reviews using (order_id)
Group by review_score
Order by average_delivery_time desc

select seller_id, avg(review_score) from sellers_products
join order_items_dataset using (seller_id)
join order_reviews using(order_id) 
Group by seller_id
Order by avg(review_score) desc
-- Ans
-- Positive values = delivered late.
-- Negative values = delivered early.
-- If lower review scores have higher positive delays, then delays contribute to poor reviews.

-- Q47. Are delivery delays linked to negative reviews?
select review_score, avg(datediff(order_delivered_customer_date,order_estimated_delivery_date)) as average_delivery_time from orders_dataset
join order_reviews using (order_id)
Group by review_score
Order by average_delivery_time desc
-- Ans is Yes

-- Q48. How do monthly order volumes fluctuate?
select Year(order_purchase_timestamp) as Year, MONTH(order_purchase_timestamp) as Month, count(*) from orders_dataset
Group by Year, Month
Order by Year, Month

-- Q49. Are there seasonal spikes in sales?
select MONTH(order_purchase_timestamp) as Month, sum(payment_value) as Revenue, count(*) from orders_dataset
join order_payments using(order_id)
Group by Month
Order by Month

-- Q50. Which months are the busiest?
select MONTH(order_purchase_timestamp) as Month, count(*) from orders_dataset
Group by Month
Order by count(*) desc

-- Q51. Which months generate the highest customer satisfaction?
select MONTH(order_purchase_timestamp) as Month, ROUND(avg(review_score),1) as satisfaction from order_reviews
join orders_dataset using (order_id)
Group by Month
Order by satisfaction desc

-- Q52. Which periods require additional operational resources?
select MONTH(order_purchase_timestamp) as Month, count(*) from orders_dataset
Group by Month
Order by count(*) desc

-- Q53. Which product categories should Olist prioritize for growth?
select product_category_name, ROUND(sum(payment_value),2) as Total_Payment from order_products
join order_items_dataset using (product_id)
join order_payments using (order_id)
Group by product_category_name
Order by Total_Payment desc

-- Q54. Which sellers should be rewarded for exceptional performance?
select seller_id, ROUND(sum(price),2) from order_items_dataset
join sellers_products using (seller_id )
Group by seller_id
Order by sum(price) desc
Limit 10;

-- Q55. Which regions require logistics improvements?
select CASE
when customer_state IN ('SP', 'RJ', 'MG', 'ES') then 'Southeast'
when customer_state IN ('PR', 'RS', 'SC') then 'South'
when customer_state IN ('GO', 'MT', 'MS', 'DF') then 'Central-West'
when customer_state IN ('BA', 'CE', 'RN', 'PE', 'PB', 'PI', 'AL', 'SE', 'MA') then 'Northeast'
when customer_state IN ('PA', 'AM', 'AP', 'RO', 'TO', 'AC', 'RR') then 'North' 
END as Regions,
avg(datediff(order_delivered_customer_date,order_purchase_timestamp)) as average_delivery_time from orders_dataset
join customers_dataset using(customer_id)
GROUP BY Regions
Order by average_delivery_time asc

-- Q56. How can Olist improve customer satisfaction?
-- Q57. Which customers should be targeted through loyalty programs?
-- Q58. Which categories present the greatest business opportunities?
-- Q59. What operational bottlenecks are limiting marketplace performance?
-- Q60. What recommendations would you provide to Olist s management team?

-- ----------------------- Stored Procedure Practice

-- Create a procedure to return all orders for a given customer ID.
DELIMITER ##
create procedure Return_all_Orders (IN Enter_ID VARCHAR(50))
BEGIN
select * from orders_dataset
where customer_id = Enter_ID;
END ##
DELIMITER ;
call Return_all_Orders('06b8999e2fba1a1fbc88172c00ba8bc7');

-- Create a procedure to return all orders placed in a given month.
DELIMITER %%
create procedure Month_vise_Orders (IN order_month INT )
BEGIN
select * from orders_dataset
where MONTH(order_purchase_timestamp) = order_month;
END %%
Delimiter ;
call Month_vise_Orders('5')

-- Create a trigger that ensures review scores stay between 1 and 5.
DELIMITER //
create trigger Score_review  
BEFORE INSERT ON order_reviews
FOR EACH ROW
BEGIN
	IF NEW.review_score < 1 OR NEW.review_score > 5 THEN
	SIGNAL SQLSTATE '11111'
    SET Message_Text = 'Please enter the value between 1 to 5.';
    END IF;
END //
DELIMITER ;

-- Create a trigger that prevents delivery dates earlier than purchase dates.
DELIMITER //
create trigger prevents_delivery_dates  
BEFORE INSERT ON orders_dataset
FOR EACH ROW
BEGIN
	IF NEW.order_estimated_delivery_date < NEW.order_purchase_timestamp THEN
    SIGNAL SQLSTATE '45000'
    SET Message_Text = 'Estimate delievery date should be after purchase date';
    END IF;
END //
DELIMITER ;

-- Create a trigger that automatically flags delayed orders. ??????????????????????????????
ALTER table orders_dataset
Add column is_delayed VARCHAR (90);

DELIMITER //
create trigger automaticallyflags_delayed_orders  
BEFORE UPDATE ON orders_dataset
FOR EACH ROW
BEGIN
	IF NEW.order_estimated_delivery_date < NEW.order_delivered_customer_date THEN
    SET NEW.is_delayed = 'Delayed';
    ELSE SET NEW.is_delayed = 'On Time';
    END IF;
END //
DELIMITER ;

-- Create a trigger that updates a seller statistics table whenever a new order item is inserted.
create table seller_statistics(
Seller_ID varchar(90),
Product_Sold varchar(90),
Price FLOAT);

Alter table seller_statistics
Add PRIMARY KEY(Seller_ID),
MODIFY COLUMN Product_Sold INT DEFAULT 0,
MODIFY COLUMN Price INT DEFAULT 0;

DELIMITER //
create trigger update_seller_statistics
AFTER INSERT on order_items_dataset
FOR EACH ROW
BEGIN
	insert into seller_statistics (Seller_ID,Product_Sold, Price) 
    values (NEW.Seller_ID, 1, NEW.Price )
    
    ON duplicate KEY UPDATE
    Product_Sold = Product_Sold +1,
    Revenue = Revenue + NEW.Price;
END//
DELIMITER ;

-- Create a trigger that stores old order values before updates.

CREATE TABLE order_items_audit (
    audit_id INT AUTO_INCREMENT PRIMARY KEY,
    order_id VARCHAR(50),
    seller_id VARCHAR(50),
    product_id VARCHAR(50),
    price DECIMAL(10,2),
    freight_value DECIMAL(10,2),
    updated_at DATETIME );

DELIMITER //
create trigger stores_old_order_values
BEFORE UPDATE on order_items_dataset
FOR EACH ROW
BEGIN
	INSERT INTO order_items_audit (order_id,seller_id,product_id,price,freight_value,updated_at)
    VALUES(OLD.order_id,OLD.seller_id,OLD.product_id,OLD.price,OLD.freight_value,NOW());
END //
DELIMITER ;

describe order_items_dataset

select * from customers_dataset;
select * from geolocation_fixed;
select * from order_items_dataset;
select * from order_payments;
select * from order_products;
select * from order_reviews;
select * from orders_dataset;
select * from product_category_name_translation;
select * from sellers_products;

